const initialProjects = [
  { id: 1, name: 'Website refresh', description: 'A sharper, simpler home for our next chapter.', deadline: '2026-10-12', color: 'lavender', notes: 'Keep the experience light, focused and unmistakably ours.', tasks: [{id:11,text:'Gather visual references',done:true},{id:12,text:'Map the new site structure',done:true},{id:13,text:'Design the landing page',done:false},{id:14,text:'Review with the team',done:false}] },
  { id: 2, name: 'Mobile app launch', description: 'Bring the product to people wherever they are.', deadline: '2026-11-04', color: 'mint', notes: 'The first release should feel effortless from the first tap.', tasks: [{id:21,text:'Finalize onboarding flow',done:true},{id:22,text:'Prepare App Store assets',done:false},{id:23,text:'Run beta testing',done:false}] },
  { id: 3, name: 'Q4 planning', description: 'Make space for ambitious, meaningful work.', deadline: '2026-09-30', color: 'peach', notes: 'Choose fewer priorities, then give them your full attention.', tasks: [{id:31,text:'Review Q3 outcomes',done:true},{id:32,text:'Set quarterly goals',done:true},{id:33,text:'Share the plan',done:true}] }
];
let projects = JSON.parse(localStorage.getItem('project-data')) || initialProjects;
let selectedId = null; let calendarDate = new Date(2026, 8, 1);
const $ = s => document.querySelector(s); const $$ = s => document.querySelectorAll(s);
const save = () => localStorage.setItem('project-data', JSON.stringify(projects));
const dateFormat = d => new Date(d + 'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'});
const getProgress = p => p.tasks.length ? Math.round(p.tasks.filter(t=>t.done).length/p.tasks.length*100) : 0;
function go(view){ $$('.view').forEach(v=>v.classList.remove('active-view')); $(`#${view}-view`).classList.add('active-view'); $$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view)); if(view==='projects') renderProjects(); if(view==='calendar') renderCalendar(); $('.sidebar').classList.remove('open'); window.scrollTo({top:0,behavior:'smooth'}); }
function renderProjects(){ const grid=$('#project-grid'); $('#project-count').textContent=projects.length; $('#task-count').textContent=projects.reduce((n,p)=>n+p.tasks.filter(t=>t.done).length,0); $('#due-count').textContent=projects.filter(p=>p.deadline.slice(0,7)==='2026-09').length; if(!projects.length){grid.innerHTML='<div class="empty-state"><h3>Your next chapter starts here.</h3><p>Create a project and turn your ideas into momentum.</p><button class="button primary" id="empty-new">Create a project</button></div>'; $('#empty-new').onclick=openModal;return;} grid.innerHTML=projects.map(p=>`<article class="project-card" data-id="${p.id}"><div class="card-top"><span class="project-dot ${p.color}"></span><span class="more">•••</span></div><h3>${p.name}</h3><p>${p.description||'No description yet.'}</p><div class="progress-meta"><span>Progress</span><strong>${getProgress(p)}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${getProgress(p)}%"></div></div><div class="card-bottom"><span>${p.tasks.filter(t=>t.done).length} of ${p.tasks.length} tasks</span><span>Due ${dateFormat(p.deadline)}</span></div></article>`).join(''); $$('.project-card').forEach(c=>c.onclick=()=>{selectedId=+c.dataset.id;renderDetails();go('details')}); }
function renderDetails(){const p=projects.find(x=>x.id===selectedId); if(!p)return; $('#project-details').innerHTML=`<div class="detail-head"><div><p class="eyebrow">Project overview</p><h1>${p.name}<span class="dot">.</span></h1><p class="detail-description">${p.description||'No description yet.'}</p></div><div class="detail-progress"><div class="progress-meta"><span>Overall progress</span><strong>${getProgress(p)}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${getProgress(p)}%"></div></div></div></div><div class="detail-layout"><div class="detail-panel"><div class="panel-heading"><h2>Tasks <span class="muted">(${p.tasks.length})</span></h2><span class="eyebrow" style="margin:0">${p.tasks.filter(t=>t.done).length} complete</span></div><div class="task-list">${p.tasks.map(t=>`<div class="task-row ${t.done?'done':''}" data-task="${t.id}"><input class="check" type="checkbox" ${t.done?'checked':''} aria-label="Mark ${t.text} complete"><span class="task-text">${t.text}</span><button class="delete-task" aria-label="Delete task">×</button></div>`).join('')}</div><form class="add-task" id="task-form"><input id="task-input" placeholder="Add a task..." required><button class="small-button">Add</button></form></div><aside class="notes-panel"><h3>Notes</h3><p>${p.notes||'Add a note to keep the important details close.'}</p><div class="deadline"><span>Deadline</span><strong>${dateFormat(p.deadline)}</strong></div></aside></div>`; $$('.check').forEach(c=>c.onchange=()=>{const t=p.tasks.find(x=>x.id===+c.closest('.task-row').dataset.task);t.done=c.checked;save();renderDetails()}); $$('.delete-task').forEach(b=>b.onclick=()=>{p.tasks=p.tasks.filter(t=>t.id!==+b.closest('.task-row').dataset.task);save();renderDetails()}); $('#task-form').onsubmit=e=>{e.preventDefault();p.tasks.push({id:Date.now(),text:$('#task-input').value,done:false});save();renderDetails()}; }
function openModal(){$('#modal-backdrop').classList.add('open');$('#project-name').focus()} function closeModal(){$('#modal-backdrop').classList.remove('open')}
$('#project-form').onsubmit=e=>{e.preventDefault();projects.push({id:Date.now(),name:$('#project-name').value,description:$('#project-description').value,deadline:$('#project-deadline').value,color:$('#project-color').value,notes:'',tasks:[]});save();e.target.reset();closeModal();go('projects')}; $('#new-project').onclick=openModal;$('#calendar-new').onclick=openModal;$('#modal-close').onclick=closeModal;$('#modal-backdrop').onclick=e=>{if(e.target.id==='modal-backdrop')closeModal()};
function renderCalendar(){const y=calendarDate.getFullYear(),m=calendarDate.getMonth();$('#calendar-month').textContent=calendarDate.toLocaleDateString('en-US',{month:'long',year:'numeric'});const first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),prev=new Date(y,m,0).getDate();let html='';for(let i=first-1;i>=0;i--)html+=`<div class="muted-day">${prev-i}</div>`;for(let d=1;d<=days;d++){const ds=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,event=projects.find(p=>p.deadline===ds);html+=`<div class="${event?'has-event':''} ${ds==='2026-09-23'?'today':''}">${d}${event?`<small>${event.name}</small>`:''}</div>`}const remaining=(7-(first+days)%7)%7;for(let d=1;d<=remaining;d++)html+=`<div class="muted-day">${d}</div>`;$('#calendar-grid').innerHTML=html}
$('#prev-month').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};$('#next-month').onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};
$('#theme-toggle').onclick=()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'':'dark';$('#theme-label').textContent=dark?'Light':'Dark';localStorage.setItem('project-theme',dark?'light':'dark')}; if(localStorage.getItem('project-theme')==='dark'){document.documentElement.dataset.theme='dark';$('#theme-label').textContent='Dark'}
$$('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.view==='projects'&&selectedId){selectedId=null}go(b.dataset.view)});$('#mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open'); const now=new Date();$('#today-label').textContent=now.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'}); renderProjects();
